(* ISO/TC184/SC4 WG12N1096 - ISO/TS - 10303-1015 Security classification - EXPRESS ARM *)
   
SCHEMA Security_classification_arm;
 
TYPE security_classification_item = EXTENSIBLE SELECT;
END_TYPE;
 
ENTITY Security_classification;
  classification_level  : STRING;
  description     : OPTIONAL STRING;
END_ENTITY; 
   
ENTITY Security_classification_assignment;
  classification  : Security_classification;
  items           : SET [1:?] OF security_classification_item;
END_ENTITY;
 
END_SCHEMA;

