(* 
  $Id$
ISO/TC184/SC4 WG12N1109 - ISO/TS 10303-1019 Product view definition - EXPRESS MIM *)
     
SCHEMA Product_view_definition_mim;

USE FROM Product_version_mim; -- ISO 10303-1018

USE FROM product_definition_schema -- ISO 10303-41
  (product_definition,
   product_definition_context_association);
USE FROM application_context_schema -- ISO 10303-41
  (product_definition_context);

END_SCHEMA;




