(* N895 - ISO/CD TS - 10303-1514 Advanced boundary representation - EXPRESS ARM *)
   
SCHEMA Advanced_boundary_representation_arm; 

   
USE FROM Boundary_representation_model_arm; -- ISO/CD TS 10303-1029

   
ENTITY Advanced_brep_shape_representation
  SUBTYPE OF (Geometric_model);
WHERE
  WR1: (SIZEOF(QUERY ( it <* SELF.items | (NOT (SIZEOF([
        'ADVANCED_BREP_SHAPE_REPRESENTATION_ARM.BREP_MODEL',
        'ADVANCED_BREP_SHAPE_REPRESENTATION_ARM.FACETED_MODEL',
        'ADVANCED_BREP_SHAPE_REPRESENTATION_ARM.TEMPLATE_INSTANCE'] * TYPEOF(it)) =
        1)) )) = 0);
END_ENTITY;

   
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
