(* N836 - ISO/CD TS - 10303-1033 Shape property representation - EXPRESS MIM *)
   SCHEMA Shape_property_representation_mim;
  USE FROM Elemental_geometric_shape_mim;               -- ISO/TS 10303-1004
  USE FROM Property_representation_mim;                 -- ISO/TS 10303-1031
  USE FROM Shape_property_assignment_mim;               -- ISO/TS 10303-1032
  USE FROM product_property_representation_schema  -- ISO 10303-41      (shape_definition_representation);
   END_SCHEMA;
(* Last update -  15 Aug 2001 *)
