(*  ISO/TC184/SC4 WG12N1976 - ISO/CD-TS - 10303-1163 individual_product_structure - EXPRESS MIM *)

SCHEMA Individual_product_structure_mim;

USE FROM Composition_of_individual_product_mim;    --  ISO/TS 10303-1166
USE FROM Connection_of_individual_product_mim;    --  ISO/TS 10303-1167
USE FROM Containment_of_individual_product_mim;    --  ISO/TS 10303-1168
USE FROM Involvement_of_individual_product_in_connection_mim;    --  ISO/TS 10303-1165
USE FROM Product_as_individual_mim;    --  ISO/TS 10303-1164

END_SCHEMA;
