(* N859 - ISO/CD TS - 10303-1029 Boundary representation model - EXPRESS ARM *)
   
SCHEMA Boundary_representation_model_arm;

   
USE FROM Topologically_bounded_surface_arm; -- ISO/TS 10303-1511
USE FROM Solid_model; -- ISO/TS 10303-1045

   
ENTITY BREP_model
  SUBTYPE OF (Solid_model); 
END_ENTITY;

   
ENTITY BREP_with_voids
  SUBTYPE OF(BREP_model); 
END_ENTITY;

   
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
