(*
ISO TC184/SC4/WG12 N1409 - ISO/CD-TS 10303-1240 Organization type - EXPRESS ARM
*) 


SCHEMA Organization_type_arm; 

USE FROM Person_organization_arm;    -- ISO/TS 10303-1011


ENTITY Organization_organization_type_relationship;
  organization : Organization;
  organization_type : Organization_type;
END_ENTITY;

ENTITY Organization_type;
  description : OPTIONAL STRING;
  name : STRING;
END_ENTITY;

END_SCHEMA;  -- Organization_type_arm

