(* ISO/TC184/SC4 WG12N1247 - ISO/TS - 10303-1040  Process property assignment- EXPRESS MIM *)

SCHEMA process_property_assignment_mim;

USE FROM Activity_method_mim;

USE FROM Activity_mim;

USE FROM Foundation_representation_mim;	

USE FROM Independent_property_mim;

USE FROM process_property_schema
  (action_property,
   characterized_action_definition);

USE FROM process_property_representation_schema
  (action_property_representation);   -- ISO 10303-49

END_SCHEMA;
