(*  ISO/TC184/SC4 WG12N1963 - ISO/CD-TS - 10303-1158 class_of_composition_of_product - EXPRESS MIM *)

SCHEMA Class_of_composition_of_product_mim;

USE FROM Class_mim;    --  ISO/TS 10303-1070
USE FROM Class_of_product_mim;    --  ISO/TS 10303-1077
USE FROM Product_version_relationship_mim;    --  ISO/TS 10303-1020

ENTITY class_of_composition_of_product
  SUBTYPE OF (product_definition_formation_relationship, class);
  SELF\product_definition_formation_relationship.relating_product_definition_formation : class_of_product;
  SELF\product_definition_formation_relationship.related_product_definition_formation : class_of_product;
END_ENTITY;

END_SCHEMA;
