(* N856 - ISO/CD TS - 10303-1028 Geometric shape with topology - EXPRESS ARM *)
   
SCHEMA Geometric_shape_with_topology_arm;

   
USE FROM Elemental_geometric_shape_arm; -- ISO/TS 10303-1004

USE FROM Elemental_topology_arm; -- ISO/TS 10303-1005

   
ENTITY Geometry_with_topology
  ABSTRACT SUPERTYPE
  SUBTYPE OF (Detailed_geometric_model_element,
              Detailed_topological_model_element);
END_ENTITY;

   
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
