(*
 $Id$
 ISO TC184/SC4/WG12N1365 - ISO/CD-TS 10303-1250 Attachment slot - EXPRESS MIM
*) 

SCHEMA Attachment_slot_mim; 

USE FROM Interface_mim;    -- ISO/CD-TS 10303-1251

USE FROM product_definition_schema   -- ISO 10303-41
  (product_category,
   product_definition,
   product_definition_formation,
   product_definition_formation_relationship,
   product_definition_relationship,
   product_related_product_category); 

USE FROM Product_identification_mim;    -- ISO/TS 10303-1017

USE FROM Product_version_mim;    -- ISO/TS 10303-1018

USE FROM Product_view_definition_mim;    -- ISO/TS 10303-1019


ENTITY product_in_slot
  SUBTYPE OF (product_definition_relationship);
END_ENTITY;

ENTITY slot_as_planned
  SUBTYPE OF (product_definition_formation);
END_ENTITY;

ENTITY slot_as_realized
  SUBTYPE OF (product_definition_formation);
END_ENTITY;

ENTITY slot_design
  SUBTYPE OF (product_definition_formation);
END_ENTITY;

ENTITY slot_design_to_planned
  SUBTYPE OF (product_definition_formation_relationship);
  SELF\product_definition_formation_relationship.related_product_definition_formation : slot_as_planned;
  SELF\product_definition_formation_relationship.relating_product_definition_formation : slot_design;
WHERE
  WR1: SELF.relating_product_definition_formation.of_product :=: SELF.related_product_definition_formation.of_product;
END_ENTITY;

ENTITY slot_design_to_realized
  SUBTYPE OF (product_definition_formation_relationship);
  SELF\product_definition_formation_relationship.related_product_definition_formation : slot_as_realized;
  SELF\product_definition_formation_relationship.relating_product_definition_formation : slot_design;
WHERE
  WR1: SELF.relating_product_definition_formation.of_product :=: SELF.related_product_definition_formation.of_product;
END_ENTITY;

ENTITY slot_on_product
  SUBTYPE OF (product_definition_relationship);
END_ENTITY;

ENTITY slot_planned_to_realized
  SUBTYPE OF (product_definition_formation_relationship);
  SELF\product_definition_formation_relationship.related_product_definition_formation : slot_as_realized;
  SELF\product_definition_formation_relationship.relating_product_definition_formation : slot_as_planned;
WHERE
  WR1: SELF.relating_product_definition_formation.of_product :=: SELF.related_product_definition_formation.of_product;
END_ENTITY;

END_SCHEMA;  -- Attachment_slot_mim
