(*
   $Id$
   ISO/TC184/SC4 WG12N1755 - ISO/CD-TS 10303-1113 Group - EXPRESS MIM
*)

SCHEMA Group_mim;

USE FROM group_schema(
  group,
  group_relationship);

USE FROM management_resources_schema(
  group_assignment);

TYPE groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT;
WHERE
WR1: NOT ('GROUP_MIM.GROUP' IN TYPEOF(SELF));
END_TYPE;

ENTITY applied_group_assignment 
SUBTYPE OF (group_assignment);
   items : SET [1:?] OF groupable_item; 
END_ENTITY;

END_SCHEMA;
