(*
 $Id$
 ISO TC184/SC4/WG12 N2787 - ISO/TS 10303-1175 Individual activity structure - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N1856
*)

SCHEMA Individual_activity_structure_mim;

USE FROM Composition_of_individual_activity_mim;    -- ISO/TS 10303-1177
USE FROM Connection_of_individual_activity_mim;    -- ISO/TS 10303-1178
USE FROM Individual_activity_mim;    -- ISO/TS 10303-1176
USE FROM Individual_involvement_in_activity_mim;    -- ISO/TS 10303-1179

END_SCHEMA;
