(* ISO/TC184/SC4 WG12N1148 - ISO/TS - 10303-1044 Certification - EXPRESS MIM *)     

SCHEMA Certification_mim;

USE FROM certification_schema -- ISO 10303-41
  (certification);
USE FROM management_resources_schema -- ISO 10303-41
  (certification_assignment);
  
TYPE certification_item = EXTENSIBLE SELECT; 
END_TYPE;
   
ENTITY applied_certification_assignment
  SUBTYPE OF (certification_assignment);
  items : SET [1:?] OF certification_item;
END_ENTITY;

END_SCHEMA;







