(* THIS IS DOCUMENT ISO TC184/SC4/WG12 N1385 *)

SCHEMA product_property_feature_definition_arm;

ENTITY product_property_feature_definition
  ABSTRACT SUPERTYPE;
END_ENTITY; --product_property_feature_definition

ENTITY product_property_instanced_feature
  SUBTYPE OF (product_property_feature_definition);
END_ENTITY; --product_property_instanced_feature

ENTITY product_property_instanced_feature_relationship;
  id: identifier;
  relating_feature: product_property_instanced_feature;
  related_feature: product_property_instanced_feature;
UNIQUE
  UR1: id, 
       relating_feature,
       related_feature;
WHERE
  WR1: relating_feature :<>: related_feature;
END_ENTITY; --product_property_instanced_feature_relationship

END_SCHEMA;

