(* N812 - ISO/CD TS - 10303-1125 File properties - EXPRESS MIM *)
   
SCHEMA File_properties_mim; 
USE FROM Property_assignment_mim; -- ISO/CD TS 10303-1030
USE FROM File_identification_mim; -- ISO/CD TS 10303-1127
USE FROM External_item_identification_assignment_mim; -- ISO/CD TS 10303-1128
USE FROM external_reference_schema -- ISO 10303-41
  (external_source);
USE FROM representation_schema -- ISO 10303-43
  (representation);
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
