(* 
   $Id$
   ISO/TC184/SC4 WG12N1794 - ISO/CD-TS 10303-1341 Generic-expression - Express MIM 
*)

SCHEMA Generic_expression_mim;

USE FROM Expression_mim;

USE FROM ISO13584_generic_expressions_schema(
	generic_expression,
	binary_generic_expression,
	environment,
	generic_variable,
	variable_semantics,
	generic_literal,
	simple_generic_expression,
	unary_generic_expression,
	multiple_arity_generic_expression);
	
USE FROM ISO13584_expressions_schema(
	variable);

END_SCHEMA;
