(*
 $Id$
 ISO/TC184/SC4 WG12N1345 - ISO/CD-TS - 10303-1070 Class - EXPRESS ARM 
*)

SCHEMA Class_arm; 


ENTITY Class
  SUPERTYPE OF (ONEOF (Class_by_extension,
                       Class_by_intension));
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

ENTITY Class_by_extension
  SUBTYPE OF (Class);
END_ENTITY;

ENTITY Class_by_intension
  SUBTYPE OF (Class);
END_ENTITY;

END_SCHEMA;  -- Class_arm
