(*  ISO/TC184/SC4 WG12N1837 - ISO/CD-TS - 10303-1170 class_of_activity_structure - EXPRESS ARM*)

SCHEMA Class_of_activity_structure_arm;

USE FROM Class_of_activity_arm;    -- ISO/TS 10303-1071
USE FROM Class_of_composition_of_activity_arm;    -- ISO/TS 10303-1171
USE FROM Class_of_connection_of_activity_arm;    -- ISO/TS 10303-1172
USE FROM Class_of_involvement_in_activity_arm;    -- ISO/TS 10303-1173

END_SCHEMA;
