(*  ISO/TC184/SC4 WG12N1990 - ISO/CD-TS - 10303-1168 containment_of_individual_product - EXPRESS MIM *)

SCHEMA Containment_of_individual_product_mim;

USE FROM Product_as_individual_mim;    --  ISO/TS 10303-1164
USE FROM Product_version_relationship_mim;    --  ISO/TS 10303-1020

ENTITY containment_of_individual_product
  SUBTYPE OF (product_definition_formation_relationship);
  SELF\product_definition_formation_relationship.relating_product_definition_formation : product_as_individual;
  SELF\product_definition_formation_relationship.related_product_definition_formation : product_as_individual;
END_ENTITY;

END_SCHEMA;
