(* ISO/TC184/SC4 WG12N1231  ISO/TS 10303-1034 
$Id$ *)

SCHEMA Product_view_definition_properties_arm;

USE FROM Product_view_definition_arm;

USE FROM Product_view_definition_relationship_arm;

USE FROM Property_assignment_arm;

TYPE product_property_assignment = EXTENSIBLE SELECT BASED_ON property_assignment_select WITH
  (Product_view_definition,
   View_definition_relationship);
END_TYPE;

END_SCHEMA;