(* ISO/TC184/SC4 WG12N1147 - ISO/TS - 10303-1044 Certification - EXPRESS ARM *)
   
SCHEMA Certification_arm;
 
TYPE certification_item = EXTENSIBLE SELECT;
END_TYPE;

ENTITY Certification;
  name           : STRING;
  description    : OPTIONAL STRING;
END_ENTITY;
 
ENTITY Certification_assignment;
  assigned_certification : Certification;
  role                   : STRING;
  items                  : SET [1:?] OF certification_item;
END_ENTITY;
 
END_SCHEMA;


