(*  ISO/TC184/SC4 WG12N1980 - ISO/CD-TS - 10303-1165 involvement_of_individual_product_in_connection - EXPRESS ARM *)

SCHEMA Involvement_of_individual_product_in_connection_arm;

USE FROM Connection_of_individual_product_arm;    --  ISO/TS 10303-1167
USE FROM Product_as_individual_arm;    --  ISO/TS 10303-1164
USE FROM Product_version_relationship_arm;    --  ISO/TS 10303-1020

ENTITY Connection_of_individual_product_with_involvements
  SUBTYPE OF (Connection_of_individual_product, Product_as_individual);
END_ENTITY;

ENTITY Involvement_of_individual_product_in_connection
  SUBTYPE OF (Product_version_relationship);
  SELF\Product_version_relationship.relating_version : Connection_of_individual_product_with_involvements;
  SELF\Product_version_relationship.related_version : Product_as_individual;
END_ENTITY;

END_SCHEMA;

