(* N866 - ISO/CD TS - 10303-1066 Constructive solid geometry - EXPRESS MIM *)
   
SCHEMA Constructive_solid_geometry_mim;
USE FROM Solid_model_mim; -- ISO 10303-1045
USE FROM Shape_property_assignment_mim; -- ISO 10303-1032
USE FROM geometric_model_schema -- ISO 10303-42
  (csg_solid,
   boolean_result);

   
ENTITY shape_aspect_transition
 SUBTYPE OF (shape_aspect_relationship);
END_ENTITY;
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
