(* ISO/TC184/SC4 WG12N1211  ISO/TS 10303-1039:2002 *)
(*  $Id$ *)

SCHEMA Geometric_validation_property_representation_mim;

USE FROM Elemental_geometric_shape_mim;

USE FROM Foundation_representation_mim;

USE FROM Measure_representation_mim;

USE FROM product_property_definition_schema
  (property_definition,
   shape_aspect);

USE FROM product_property_representation_schema
  (property_definition_representation);

END_SCHEMA;
